# -*- coding: utf-8 -*-
"""DataSoftixs-week1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPj9F_b7huMoMM3DlxyxsgvDq3tfeG9g
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/train.csv")
print("Data loaded successfully!")

print("Initial Data Info:")
print(df.info())

# Remove duplicates and handle missing values
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

# Print cleaned data info
print("\nCleaned Data Info:")
print(df.info())

# Step 3: Calculate Metrics
# Total sales
if 'Sales' in df.columns:
    total_sales = df['Sales'].sum()
    print(f"\nTotal Sales: {total_sales}")

    # Average sales
    average_sales = df['Sales'].mean()
    print(f"Average Sales: {average_sales}")
else:
    print("Error: 'Sales' column is missing in the dataset.")

# Sales trends over time
if 'Order Date' in df.columns:
    try:
        # Convert to datetime with dayfirst=True to handle dd/mm/yyyy format
        df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
        sales_trends = df.groupby(df['Order Date'].dt.to_period('M'))['Sales'].sum()
        print("\nSales Trends Over Time:")
        print(sales_trends)
    except Exception as e:
        print(f"Error: {e}")
else:
    print("Error: 'Order Date' column is missing in the dataset.")

# Step 4: Visualizations
if 'Sales' in df.columns and 'Order Date' in df.columns:
    # Bar chart: Sales trends
    sales_trends.plot(kind='bar', figsize=(10, 6), color='skyblue')
    plt.title('Monthly Sales Trends')
    plt.xlabel('Month')
    plt.ylabel('Total Sales')
    plt.xticks(rotation=45)
    plt.show()

    # Line plot: Sales trends
    sales_trends.plot(kind='line', marker='o', figsize=(10, 6))
    plt.title('Sales Trends Over Time')
    plt.xlabel('Month')
    plt.ylabel('Total Sales')
    plt.grid()
    plt.show()
else:
    print("Error: Cannot visualize sales trends due to missing columns.")